name: xml_sign_dart
description: Biblioteca para assinar XMLs e executar integracoes SEFAZ para NF-e/NFC-e em Dart.
version: 1.0.0

environment:
  sdk: '^3.9.0'

topics:
  - nfe
  - nfce
  - sefaz
  - assinatura-xml

dependencies:
  xml: ^6.6.1
  pointycastle: ^4.0.0
  basic_utils: ^5.8.2  # parser PEM/X.509/PKCS#8
  convert: ^3.1.2
  crypto: ^3.0.6

dev_dependencies:
  test: ^1.25.0
